services:
  api:
    build:
      context: .
      target: api-runner
    container_name: product-catalog-api
    env_file:
      - ./apps/api/.env
    environment:
      - JWT_EXPIRES_IN=7d
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=postgresql://admin:admin123@product-catalog-db:5432/product_catalog-db
      - DIRECT_URL=postgresql://admin:admin123@product-catalog-db:5432/product_catalog-db
    ports:
      - "3001:3001"
    networks:
      - default
    restart: unless-stopped

  web:
    build:
      context: .
      target: web-runner
    container_name: product-catalog-web
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: unless-stopped
