[phases.setup]
nixPkgs = ['nodejs_20', 'npm']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npm run db:generate --filter=@product-catalog/api', 'npm run build --filter=@product-catalog/api']

[start]
cmd = 'cd apps/api && npm start'